### ISSUE TITLE
Multiple reloads cause crash

### ISSUE THREAD

**Issue by CoolRunning** [mikeheddes/dcgp-web#52]
Reloading the page while reloading the page causes the browser to crash (reproducible by spamming F5).

**Comment by mikeheddes** [comment]
He Marcus, sad to see you are having issues with the webpage. Maybe [this tutorial](https://www.youtube.com/watch?v=n0W_2dx85Sc) will help. 

I will close this for now. If you are still having issues feel free to reopen.
