### ISSUE TITLE
Sometimes Loss Increases with Gradient Descent

### ISSUE THREAD

**Issue by Microno95** [mikeheddes/dcgp-web#55]
After finding an expression involving some constants, running gradient descent sometimes increases the loss instead of decreasing it. 

This is an example of that happening:

![loss-increases-w-gradient-descent](https://user-images.githubusercontent.com/11709271/56346304-1677a400-61c2-11e9-8df8-16f20ccd6c56.png)

**Comment by mikeheddes** [comment]
This should be fixed with #58, if you still encounter it please reopen this issue.
